apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
      - name: employee-api
        image: employee-api:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: employee_user
        - name: MYSQL_PASSWORD
          value: Jessica@117311
        - name: MYSQL_DATABASE
          value: employee_db
---
apiVersion: v1
kind: Service
metadata:
  name: employee-api
spec:
  type: NodePort
  selector:
    app: employee-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30261  
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Jessica@117311
        - name: MYSQL_DATABASE
          value: employee_db
        - name: MYSQL_USER
          value: employee_user
        - name: MYSQL_PASSWORD
          value: Jessica@117311
        volumeMounts:
        - name: mysql-init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-init-script
        configMap:
          name: mysql-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:  
  - port: 3306
  type: ClusterIP 

  