"""create employees table

Revision ID: d644a4415b44
Revises: e3e6f3cdd5ab
Create Date: 2025-05-12 13:18:23.236194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd644a4415b44'
down_revision = 'e3e6f3cdd5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('last_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'last_name')
    # ### end Alembic commands ###

